bash doesn't have else if, it has else and if

diff --git a/.github/actions/python/pypi-deploy/action.yaml b/.github/actions/python/pypi-deploy/action.yaml
--- a/.github/actions/python/pypi-deploy/action.yaml
+++ b/.github/actions/python/pypi-deploy/action.yaml
@@ -19,11 +19,13 @@ runs:
           echo '::set-env name=SWALLOW_FAILURE::"|| echo \"Duplicate upload allowed on test\""'
           echo "Uploading to test pypi"
         else if [[ ${{ inputs.repository_url }} =~ "upload.pypi.org" ]]; then
-          echo "Uploading to prod pypi"
-        else
-          echo "::error ::Invalid repository url ${{ inputs.repository_url }}"
-          exit 1
+                 echo "Uploading to prod pypi"
+             else
+                 echo "::error ::Invalid repository url ${{ inputs.repository_url }}"
+                 exit 1
+             fi
         fi
+
 
     - shell: bash
       run: 'QUIET=1 BUILD_NUMBER=${OT_BUILD} make -C ${{ inputs.project }} clean deploy twine_repository_url=${{ inputs.repository_url }} pypi_username=opentrons pypi_password=${{ inputs.password }} ${SWALLOW_FAILURE}'
