indent fix

diff --git a/.github/actions/python/pypi-deploy/action.yaml b/.github/actions/python/pypi-deploy/action.yaml
--- a/.github/actions/python/pypi-deploy/action.yaml
+++ b/.github/actions/python/pypi-deploy/action.yaml
@@ -18,18 +18,19 @@ runs:
         if [[ ${{ inputs.repository_url }} =~ "test" ]]; then
           echo "Uploading to test pypi"
         else if [[ ${{ inputs.repository_url }} =~ "upload.pypi.org" ]]; then
-                 echo "Uploading to prod pypi"
-                 # this needs to be cleared otherwise the makefiles append a dev tag
-                 OT_BUILD=
-             else
-                 echo "::error ::Invalid repository url ${{ inputs.repository_url }}"
-                 exit 1
-             fi
+          echo "Uploading to prod pypi"
+          # this needs to be cleared otherwise the makefiles append a dev tag
+          OT_BUILD=
+                 
+          else
+            echo "::error ::Invalid repository url ${{ inputs.repository_url }}"
+            exit 1
+          fi
         fi
         status=0
         QUIET=1 BUILD_NUMBER=${OT_BUILD} make -C ${{ inputs.project }} clean deploy twine_repository_url=${{ inputs.repository_url }} pypi_username=opentrons pypi_password=${{ inputs.password }} || status=$?
         if [[ ${status} != 0 ]] && [[ ${{ inputs.repository_url }} =~ "test.pypi.org" ]]; then
-           echo "upload failures allowed to test pypi"
-           exit 0
+          echo "upload failures allowed to test pypi"
+          exit 0
         fi
         exit ${status}
