i hate embedding things in yaml so much

diff --git a/.github/actions/python/pypi-deploy/action.yaml b/.github/actions/python/pypi-deploy/action.yaml
--- a/.github/actions/python/pypi-deploy/action.yaml
+++ b/.github/actions/python/pypi-deploy/action.yaml
@@ -16,7 +16,7 @@ runs:
       run: |
         echo "::add-mask::${{ inputs.password }}"
         if [[ ${{ inputs.repository_url }} =~ "test" ]]; then
-          echo "::set-env name=SWALLOW_FAILURE::"|| echo \"Duplicate upload allowed on test\""
+          echo '::set-env name=SWALLOW_FAILURE::"|| echo \"Duplicate upload allowed on test\""'
           echo "Uploading to test pypi"
         else if [[ ${{ inputs.repository_url }} =~ "upload.pypi.org" ]]; then
           echo "Uploading to prod pypi"
