travis

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -46,7 +46,7 @@ script:
   - "export OT_COMMIT_SUFFIX=-${TRAVIS_COMMIT: -7}" # Escape -
   - cd api && make test exe && cd ..
   - > # Make docs on linux only
-    if [ "$TRAVIS_OS_NAME" == "linux" ]; then (cd api && make docs > /dev/null && cd ..) fi
+    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then (cd api && make docs > /dev/null && cd ..) fi;
   - cd app && make -j 2 build test test-e2e && make package && cd ..
   # Clean up. This will leave only single-file build artifacts
   - find ./app/dist/** ! -name 'opentrons-v*' -exec rm -rf {} +
@@ -65,7 +65,8 @@ deploy:
     upload-dir: $TRAVIS_OS_NAME
     acl: public_read
     on:
-      condition: "$TRAVIS_TEST_RESULT" = "0"
+      condition: >
+        [ "$TRAVIS_TEST_RESULT" == "0" ] || (echo "Build failed, skipping deploy") || [ 1 ]
       repo: Opentrons/opentrons
       all_branches: true
 
