chore(build): remove azure ubuntu package mirror in CI because it's broken (#7043)
Our api builds started failing on ubuntu because they couldn't install libsystemd. They appear to be hitting the package mirror http://azure.archive.ubuntu.com/ubuntu/ which as of 10 33am est today appears to have all content removed from the pool/ path.

This removes that mirror from the sources list and hopefully forces a fallback to another mirror that isn't broken in such a way.

Works around actions/virtual-environments#2104

diff --git a/.github/actions/python/setup/action.yaml b/.github/actions/python/setup/action.yaml
--- a/.github/actions/python/setup/action.yaml
+++ b/.github/actions/python/setup/action.yaml
@@ -8,7 +8,8 @@ runs:
   using: 'composite'
   steps:
     - shell: bash
-      run: '[[ "${OSTYPE}" =~ "linux" ]] && sudo apt-get install -y --no-install-recommends libsystemd-dev || echo "do nothing and avoid pipefail"'
+      run: |
+        [[ "${OSTYPE}" =~ "linux" ]] && sudo sed -i 's/azure\.//' /etc/apt/sources.list && sudo apt-get update && sudo apt-get install -y --no-install-recommends libsystemd-dev || echo "do nothing and avoid pipefail"
     - shell: bash
       run: |
         npm install --global shx@0.2.2
